parent = "core/debian-bookworm"

recipes = [
    # Set a static hostname.
    "core/set-hostname",
    # Setup and enable SSH.
    "core/ssh",
    # Setup the network.
    "setup-network",
    # Setup time synchronization.
    "setup-timesyncd",
    # Enable discovery of the system in the local network.
    "rugix-extra/avahi",
    # Install SSH key for local development.
    "install-ssh-dev-key",
    # Install the Aqago agent. 
    "aqago-rugix-recipes/aqago-agent",
    # Install the system OTA manager application.
    "aqago-rugix-recipes/system-ota-manager"
]

[parameters."core/set-hostname"]
hostname = "aqago-rugix-os"
